language: php
sudo: required
dist: bionic
group: edge

php:
  - 7.4
  - 7.3
  - 7.2

before_script:
  - composer install

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
