language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.1
  - 5.6

before_script:
  - composer install

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
